/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TripLuggageCheckImport } from './routes/tripLuggageCheck'
import { Route as StepsImport } from './routes/steps'
import { Route as DateCounterImport } from './routes/dateCounter'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TripLuggageCheckRoute = TripLuggageCheckImport.update({
  id: '/tripLuggageCheck',
  path: '/tripLuggageCheck',
  getParentRoute: () => rootRoute,
} as any)

const StepsRoute = StepsImport.update({
  id: '/steps',
  path: '/steps',
  getParentRoute: () => rootRoute,
} as any)

const DateCounterRoute = DateCounterImport.update({
  id: '/dateCounter',
  path: '/dateCounter',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/dateCounter': {
      id: '/dateCounter'
      path: '/dateCounter'
      fullPath: '/dateCounter'
      preLoaderRoute: typeof DateCounterImport
      parentRoute: typeof rootRoute
    }
    '/steps': {
      id: '/steps'
      path: '/steps'
      fullPath: '/steps'
      preLoaderRoute: typeof StepsImport
      parentRoute: typeof rootRoute
    }
    '/tripLuggageCheck': {
      id: '/tripLuggageCheck'
      path: '/tripLuggageCheck'
      fullPath: '/tripLuggageCheck'
      preLoaderRoute: typeof TripLuggageCheckImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dateCounter': typeof DateCounterRoute
  '/steps': typeof StepsRoute
  '/tripLuggageCheck': typeof TripLuggageCheckRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dateCounter': typeof DateCounterRoute
  '/steps': typeof StepsRoute
  '/tripLuggageCheck': typeof TripLuggageCheckRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dateCounter': typeof DateCounterRoute
  '/steps': typeof StepsRoute
  '/tripLuggageCheck': typeof TripLuggageCheckRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/dateCounter' | '/steps' | '/tripLuggageCheck'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/dateCounter' | '/steps' | '/tripLuggageCheck'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dateCounter'
    | '/steps'
    | '/tripLuggageCheck'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DateCounterRoute: typeof DateCounterRoute
  StepsRoute: typeof StepsRoute
  TripLuggageCheckRoute: typeof TripLuggageCheckRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DateCounterRoute: DateCounterRoute,
  StepsRoute: StepsRoute,
  TripLuggageCheckRoute: TripLuggageCheckRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/dateCounter",
        "/steps",
        "/tripLuggageCheck"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/dateCounter": {
      "filePath": "dateCounter.tsx"
    },
    "/steps": {
      "filePath": "steps.tsx"
    },
    "/tripLuggageCheck": {
      "filePath": "tripLuggageCheck.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
